[package]
name = "gol-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["gol-internal", "gol-slow"]
gol-internal = []
gol-slow = []

[dependencies]
spin = "0.9.3"
